Vagrant.configure("2") do |config|
    # Define three virtual machines
    (1..3).each do |i|
      config.vm.define "ubuntu#{i}" do |node|
        node.vm.box = "ubuntu/focal64"
        node.vm.network "private_network", type: "static", ip: "192.168.56.#{i + 10}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 2
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
  
        # Server hardening provisioning script (replace 'provision.sh' with your script)
        # node.vm.provision "shell", path: "provision.sh"
      end
    end
  end